
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ATTRIBUTE_NAME ATTRIBUTE_VALUE EQUALS GT LT SLASH SLASH_GT TAG_NAMEtag : LT TAG_NAME atributos SLASH_GT\n    comprobante : LT TAG_NAME atributos GT emisor receptor conceptos LT SLASH TAG_NAME GT\n    emisor : LT TAG_NAME atributos SLASH_GTreceptor : LT TAG_NAME atributos SLASH_GTconceptos : LT TAG_NAME GT concepto LT SLASH TAG_NAME GTconcepto : LT TAG_NAME atributos SLASH_GT\n    atributos : atributo atributos\n              | atributo\n              | empty\n    atributo : ATTRIBUTE_NAME EQUALS ATTRIBUTE_VALUEempty :'
    
_lr_action_items = {'LT':([0,],[2,]),'$end':([1,8,],[0,-1,]),'TAG_NAME':([2,],[3,]),'ATTRIBUTE_NAME':([3,5,11,],[7,7,-10,]),'SLASH_GT':([3,4,5,6,9,11,],[-11,8,-8,-9,-7,-10,]),'EQUALS':([7,],[10,]),'ATTRIBUTE_VALUE':([10,],[11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'tag':([0,],[1,]),'atributos':([3,5,],[4,9,]),'atributo':([3,5,],[5,5,]),'empty':([3,5,],[6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> tag","S'",1,None,None,None),
  ('tag -> LT TAG_NAME atributos SLASH_GT','tag',4,'p_tag_autocontenida','parser4.py',13),
  ('comprobante -> LT TAG_NAME atributos GT emisor receptor conceptos LT SLASH TAG_NAME GT','comprobante',11,'p_comprobante','parser4.py',20),
  ('emisor -> LT TAG_NAME atributos SLASH_GT','emisor',4,'p_emisor','parser4.py',30),
  ('receptor -> LT TAG_NAME atributos SLASH_GT','receptor',4,'p_receptor','parser4.py',40),
  ('conceptos -> LT TAG_NAME GT concepto LT SLASH TAG_NAME GT','conceptos',8,'p_conceptos','parser4.py',50),
  ('concepto -> LT TAG_NAME atributos SLASH_GT','concepto',4,'p_concepto','parser4.py',60),
  ('atributos -> atributo atributos','atributos',2,'p_atributos','parser4.py',70),
  ('atributos -> atributo','atributos',1,'p_atributos','parser4.py',71),
  ('atributos -> empty','atributos',1,'p_atributos','parser4.py',72),
  ('atributo -> ATTRIBUTE_NAME EQUALS ATTRIBUTE_VALUE','atributo',3,'p_atributo','parser4.py',82),
  ('empty -> <empty>','empty',0,'p_empty','parser4.py',86),
]
