
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ATTRIBUTE_NAME ATTRIBUTE_VALUE EQUALS GT LT SLASH TAG_NAMEcomprobante : LT TAG_NAME atributos GT emisor receptor conceptos LT SLASH TAG_NAME GTemisor : LT TAG_NAME atributos SLASH GTreceptor : LT TAG_NAME atributos SLASH GTconceptos : LT TAG_NAME GT concepto LT SLASH TAG_NAME GTconcepto : LT TAG_NAME atributos SLASH GTatributos : atributo atributos\n                 | atributoatributo : ATTRIBUTE_NAME EQUALS ATTRIBUTE_VALUE'
    
_lr_action_items = {'LT':([0,7,11,15,19,24,26,28,30,39,40,],[2,10,14,18,23,-2,29,-3,33,-5,-4,]),'$end':([1,34,],[0,-1,]),'TAG_NAME':([2,10,14,18,27,29,36,],[3,13,17,22,31,32,38,]),'ATTRIBUTE_NAME':([3,5,12,13,17,32,],[6,6,-8,6,6,6,]),'GT':([4,5,8,12,20,22,25,31,37,38,],[7,-7,-6,-8,24,26,28,34,39,40,]),'SLASH':([5,8,12,16,21,23,33,35,],[-7,-6,-8,20,25,27,36,37,]),'EQUALS':([6,],[9,]),'ATTRIBUTE_VALUE':([9,],[12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'comprobante':([0,],[1,]),'atributos':([3,5,13,17,32,],[4,8,16,21,35,]),'atributo':([3,5,13,17,32,],[5,5,5,5,5,]),'emisor':([7,],[11,]),'receptor':([11,],[15,]),'conceptos':([15,],[19,]),'concepto':([26,],[30,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> comprobante","S'",1,None,None,None),
  ('comprobante -> LT TAG_NAME atributos GT emisor receptor conceptos LT SLASH TAG_NAME GT','comprobante',11,'p_comprobante','parser4.py',10),
  ('emisor -> LT TAG_NAME atributos SLASH GT','emisor',5,'p_emisor','parser4.py',17),
  ('receptor -> LT TAG_NAME atributos SLASH GT','receptor',5,'p_receptor','parser4.py',24),
  ('conceptos -> LT TAG_NAME GT concepto LT SLASH TAG_NAME GT','conceptos',8,'p_conceptos','parser4.py',31),
  ('concepto -> LT TAG_NAME atributos SLASH GT','concepto',5,'p_concepto','parser4.py',38),
  ('atributos -> atributo atributos','atributos',2,'p_atributos','parser4.py',45),
  ('atributos -> atributo','atributos',1,'p_atributos','parser4.py',46),
  ('atributo -> ATTRIBUTE_NAME EQUALS ATTRIBUTE_VALUE','atributo',3,'p_atributo','parser4.py',50),
]
